[client]
showSidebarNavigation = false
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#355CFF"
backgroundColor = "#F6F8FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#18212F"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false